version: '3.8'
name: providenie

services:
  bot:
    build: .
    restart: always
    env_file:
      - ./src/.env
    volumes:
      - ~:/app/bot/.data/
    depends_on:
      - db

  db:
    env_file:
      - ./src/.env
    image: postgres:17-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


volumes:
  db_data:
